import type { MoveFamily, MovePattern } from './families';

/**
 * The authored move catalogue (`V33-041`, v3.3 section D2).
 *
 * ## What this is
 *
 * Every move this product may ever propose, written out in full and reviewed as text.
 * There is no template and no composition step: if a sentence is not in this file, no code
 * path can construct it. That is the same discipline `HEALTH_ACTIONS` established for the
 * one domain that could hurt someone, extended to all of them now that the catalogue is
 * large enough that a generator would have been tempting.
 *
 * The application may **personalise** what is here — filling in the owner's own goal, the
 * commitment they named, the practice they wrote down — but it may not invent a move, and
 * it must never present a filled-in template as though it were novelty.
 *
 * ## Breadth without padding
 *
 * The target is a hundred or so genuinely distinct patterns. Every one declares
 * `distinctBecause`, and `tests/unit/moveCatalogue.test.ts` fails the build if two
 * patterns in a family cannot be told apart, if a statement is reused, or if a family's
 * variants collapse into rewordings of each other. A number reached by renaming is worse
 * than a smaller honest number, because it makes the catalogue look richer than the
 * owner's actual set of options.
 *
 * ## What is deliberately absent
 *
 * No calorie, macro, rep count, dose, supplement, medication, diagnosis, symptom
 * interpretation, or treatment claim. Not filtered — absent. The vocabulary does not
 * contain them.
 */

/* -------------------------------------------------------------------------- */
/* Families                                                                     */
/* -------------------------------------------------------------------------- */

export const MOVE_FAMILIES: readonly MoveFamily[] = [
  {
    familyId: 'pause',
    label: 'Step away',
    purpose: 'restore',
    domains: ['health-recovery-energy', 'emotional-and-relationships'],
    decisionJob: 'Interrupt whatever is currently costing more than it returns.',
  },
  {
    familyId: 'move-body',
    label: 'Move',
    purpose: 'restore',
    domains: ['health-recovery-energy'],
    decisionJob: 'Change physical state when sitting still is part of the problem.',
  },
  {
    familyId: 'hydrate-eat',
    label: 'Eat or drink something',
    purpose: 'restore',
    domains: ['health-recovery-energy'],
    decisionJob: 'Rule out the ordinary physical explanations before anything clever.',
  },
  {
    familyId: 'wind-down',
    label: 'Wind down',
    purpose: 'protect',
    domains: ['health-recovery-energy'],
    decisionJob: 'Protect tonight’s sleep from today’s momentum.',
  },
  {
    familyId: 'settle-attention',
    label: 'Settle',
    purpose: 'restore',
    domains: ['health-recovery-energy', 'emotional-and-relationships', 'faith-and-meaning'],
    decisionJob: 'Bring attention back when it is scattered rather than tired.',
  },
  {
    familyId: 'protect-a-block',
    label: 'Protect a block',
    purpose: 'protect',
    domains: ['career-and-learning'],
    decisionJob: 'Defend uninterrupted time for the thing that actually matters today.',
  },
  {
    familyId: 'smallest-next-step',
    label: 'The smallest next step',
    purpose: 'unblock',
    domains: ['career-and-learning', 'home-and-environment', 'money'],
    decisionJob: 'Move a stalled thing by the smallest increment that is genuinely real.',
  },
  {
    familyId: 'unblock-by-asking',
    label: 'Ask someone',
    purpose: 'unblock',
    domains: ['career-and-learning', 'money', 'home-and-environment'],
    decisionJob: 'Restart something that is waiting on another person.',
  },
  {
    familyId: 'decide-and-close',
    label: 'Decide it',
    purpose: 'unblock',
    domains: ['career-and-learning', 'money', 'home-and-environment'],
    decisionJob: 'End the cost of an open decision that is not getting better with time.',
  },
  {
    familyId: 'prepare-the-ground',
    label: 'Set it up',
    purpose: 'prepare',
    domains: ['career-and-learning', 'home-and-environment', 'health-recovery-energy'],
    decisionJob: 'Remove the friction that will otherwise stop the real thing happening.',
  },
  {
    familyId: 'find-out',
    label: 'Find out',
    purpose: 'learn',
    domains: ['career-and-learning', 'money', 'health-recovery-energy'],
    decisionJob: 'Replace a guess that is currently driving a decision with a fact.',
  },
  {
    familyId: 'reach-out',
    label: 'Reach someone',
    purpose: 'connect',
    domains: ['emotional-and-relationships', 'fatherhood'],
    decisionJob: 'Tend a relationship before it needs repairing.',
  },
  {
    familyId: 'repair',
    label: 'Repair it',
    purpose: 'connect',
    domains: ['emotional-and-relationships', 'fatherhood'],
    decisionJob: 'Address something that went wrong between two people.',
  },
  {
    familyId: 'attend-to-child',
    label: 'Time with a child',
    purpose: 'connect',
    domains: ['fatherhood'],
    decisionJob: 'Be present in a way the child would actually notice.',
  },
  {
    familyId: 'reduce-friction-at-home',
    label: 'Take the friction out',
    purpose: 'relieve',
    domains: ['home-and-environment'],
    decisionJob: 'Remove a thing that gets in the way repeatedly, not once.',
  },
  {
    familyId: 'money-clarity',
    label: 'See the money clearly',
    purpose: 'learn',
    domains: ['money'],
    decisionJob: 'Turn a vague financial worry into something with an actual shape.',
  },
  {
    familyId: 'money-guard',
    label: 'Protect the position',
    purpose: 'protect',
    domains: ['money'],
    decisionJob: 'Keep a manageable situation from becoming an urgent one.',
  },
  {
    familyId: 'live-the-value',
    label: 'Act on what you said matters',
    purpose: 'realign',
    domains: ['faith-and-meaning'],
    decisionJob: 'Close the gap between a stated value and this week’s behaviour.',
  },
  {
    familyId: 'boundary',
    label: 'Hold a line',
    purpose: 'protect',
    domains: ['emotional-and-relationships', 'career-and-learning', 'health-recovery-energy'],
    decisionJob: 'Protect something that keeps getting eroded by something else.',
  },
  {
    familyId: 'routine-anchor',
    label: 'Anchor a routine',
    purpose: 'prepare',
    domains: ['health-recovery-energy', 'home-and-environment'],
    decisionJob:
      'Make a recurring thing happen by attaching it to something that already does.',
  },
];

/* -------------------------------------------------------------------------- */
/* Shorthands                                                                   */
/* -------------------------------------------------------------------------- */

type Effect = MovePattern['effects'][number];

const lift = (
  channel: Effect['channel'],
  magnitude: Effect['magnitude'] = 'small',
): Effect => ({ channel, effect: 'improves', magnitude });

const later = (
  channel: Effect['channel'],
  magnitude: Effect['magnitude'] = 'small',
): Effect => ({ channel, effect: 'improves-later', magnitude });

const costs = (
  channel: Effect['channel'],
  magnitude: Effect['magnitude'] = 'small',
): Effect => ({ channel, effect: 'costs', magnitude });

const guards = (
  channel: Effect['channel'],
  magnitude: Effect['magnitude'] = 'small',
): Effect => ({ channel, effect: 'protects', magnitude });

/** Every pattern is authored at version 1 until its meaning changes. */
const V = 1;

/* -------------------------------------------------------------------------- */
/* Patterns                                                                     */
/* -------------------------------------------------------------------------- */

export const MOVE_PATTERNS: readonly MovePattern[] = [
  /* --- pause ------------------------------------------------------------- */
  {
    patternId: 'pause:screen-break',
    familyId: 'pause',
    statement: 'Stop for ten minutes away from a screen',
    distinctBecause: 'The general-purpose interruption when nothing more specific is known.',
    intendedOutcome: 'Whatever is interfering eases enough to do something else',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 4 },
    observationWindow: 'immediate',
    durationMinutes: 10,
    minimumMinutes: 2,
    minimumVersion: 'Two minutes standing up, away from the desk',
    fallback: 'Sit back and stop looking at anything for a minute',
    stoppingPoint: 'Stop after ten minutes whether or not it helped',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    effects: [lift('energy-and-recovery'), later('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'pause:step-outside',
    familyId: 'pause',
    statement: 'Go outside for five minutes',
    distinctBecause:
      'Needs somewhere to go, and changes light and air rather than only stopping.',
    intendedOutcome: 'You come back to the task having genuinely left it',
    followUp: { promptId: 'outcome:completed', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 5,
    minimumMinutes: 3,
    minimumVersion: 'Stand at an open door or window for a minute',
    fallback: 'Open a window where you are',
    stoppingPoint: 'Five minutes. This is not a walk.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'transition' },
    effects: [lift('energy-and-recovery'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'pause:close-the-loop-mentally',
    familyId: 'pause',
    statement: 'Write down where you got to, then stop',
    distinctBecause:
      'Protects the *return* rather than the break — the cost of stopping is losing your place.',
    intendedOutcome: 'Picking the work back up takes seconds rather than minutes',
    followUp: { promptId: 'outcome:returned-to-task', windowHours: 6 },
    observationWindow: 'same-day',
    durationMinutes: 3,
    minimumMinutes: 1,
    minimumVersion: 'One line: the next thing you were about to do',
    fallback: 'Leave the file open at the right place',
    stoppingPoint: 'When the note is written',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('focus-and-clarity', 'meaningful'), lift('follow-through')],
    version: V,
  },
  {
    patternId: 'pause:lie-down',
    familyId: 'pause',
    statement: 'Lie down for twenty minutes without a screen',
    distinctBecause:
      'The deep version, for depleted rather than distracted. Needs somewhere to lie down.',
    intendedOutcome: 'Energy afterwards is different from energy before',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 4 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes with your eyes shut',
    fallback: 'Sit somewhere that is not your desk',
    stoppingPoint: 'Twenty minutes. Longer starts costing tonight.',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus', interruptionCost: 'total' },
    effects: [lift('energy-and-recovery', 'meaningful'), costs('follow-through')],
    version: V,
  },

  /* --- move-body --------------------------------------------------------- */
  {
    patternId: 'move-body:gentle-ten',
    familyId: 'move-body',
    statement: 'Move gently for ten minutes — a walk, or anything that is not sitting',
    distinctBecause: 'The default movement dose when there is a gap and no constraint.',
    intendedOutcome: 'Energy after moving is different from energy before',
    followUp: { promptId: 'outcome:completed', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'Three minutes on your feet',
    fallback: 'Stand up and stretch where you are',
    stoppingPoint: 'Stop when it stops feeling easy. There is no target here.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    capacity: { shape: 'transition' },
    effects: [lift('energy-and-recovery', 'meaningful'), later('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'move-body:desk-reset',
    familyId: 'move-body',
    statement: 'Stand up and stretch for two minutes without leaving the room',
    distinctBecause: 'The version that survives an open-plan office and a full calendar.',
    intendedOutcome: 'Sitting stops being the thing making this harder',
    followUp: { promptId: 'outcome:completed', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Stand up for thirty seconds',
    fallback: 'Roll your shoulders where you sit',
    stoppingPoint: 'Two minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'move-body:walk-while-talking',
    familyId: 'move-body',
    statement: 'Take the next call on your feet',
    distinctBecause:
      'Costs no separate time at all — the only movement move available during a full day.',
    intendedOutcome: 'The day contains movement without anything being displaced',
    followUp: { promptId: 'outcome:completed', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 5,
    minimumVersion: 'Stand for part of it',
    fallback: 'Stand up for the last five minutes',
    stoppingPoint: 'When the call ends',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'parallel' },
    effects: [lift('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'move-body:longer-walk',
    familyId: 'move-body',
    statement: 'Take a walk of half an hour or so',
    distinctBecause: 'The dose that needs a real window, kept separate so it can be ruled out.',
    intendedOutcome: 'The rest of the day feels different from how it was going',
    followUp: { promptId: 'outcome:duration', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'Fifteen minutes is most of the benefit',
    fallback: 'Ten minutes around the block',
    stoppingPoint: 'When you get back',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'exclusive-time' },
    effects: [lift('energy-and-recovery', 'meaningful'), lift('emotional-regulation')],
    version: V,
  },

  /* --- hydrate-eat -------------------------------------------------------- */
  {
    patternId: 'hydrate-eat:water',
    familyId: 'hydrate-eat',
    statement: 'Have a glass of water',
    distinctBecause: 'The cheapest possible check, available in every situation.',
    intendedOutcome: 'One ordinary explanation for feeling flat is ruled out',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 2 },
    observationWindow: 'immediate',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'A few mouthfuls',
    fallback: 'Put a glass within reach for later',
    stoppingPoint: 'One glass. This is not a hydration target.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    effects: [lift('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'hydrate-eat:eat-something',
    familyId: 'hydrate-eat',
    statement: 'Eat something before the next block',
    distinctBecause: 'The other ordinary explanation, and a genuine prerequisite for focus.',
    intendedOutcome: 'Hunger stops being a candidate explanation',
    followUp: { promptId: 'outcome:completed', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Anything at all, standing up',
    fallback: 'Put something within reach for the next break',
    stoppingPoint: 'When you have eaten',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'supported',
    effects: [lift('energy-and-recovery', 'meaningful')],
    version: V,
  },
  {
    patternId: 'hydrate-eat:eat-before-evening',
    familyId: 'hydrate-eat',
    statement: 'Eat earlier than usual tonight',
    distinctBecause:
      'Aimed at tonight’s sleep rather than this afternoon’s energy — a different window entirely.',
    intendedOutcome: 'Falling asleep takes less time than last night',
    followUp: { promptId: 'sleep:onset-minutes', windowHours: 16 },
    observationWindow: 'next-morning',
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'Even half an hour earlier is the experiment',
    fallback: 'Keep tonight’s meal lighter than usual',
    stoppingPoint: 'When the meal is over',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [later('energy-and-recovery', 'meaningful')],
    version: V,
  },

  /* --- wind-down ---------------------------------------------------------- */
  {
    patternId: 'wind-down:start-now',
    familyId: 'wind-down',
    statement: 'Start winding down for sleep now rather than later',
    distinctBecause: 'The full version, when there is still time for it to work.',
    intendedOutcome: 'Falling asleep takes less time than last night',
    followUp: { promptId: 'sleep:onset-minutes', windowHours: 16 },
    observationWindow: 'next-morning',
    durationMinutes: 20,
    minimumMinutes: 5,
    minimumVersion: 'Screens down and lights lower for five minutes',
    fallback: 'Decide what time you will stop, and set it somewhere you will see',
    stoppingPoint: 'When you go to bed. This is not a routine to complete.',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'supported',
    capacity: { shape: 'protected-focus', interruptionCost: 'total' },
    contradicts: ['protect-a-block:deep-block', 'protect-a-block:short-block'],
    effects: [later('energy-and-recovery', 'large'), guards('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'wind-down:phone-down',
    familyId: 'wind-down',
    statement: 'Put the phone somewhere else for the rest of the evening',
    distinctBecause: 'One specific change rather than a routine, and it needs no time at all.',
    intendedOutcome: 'The gap between deciding to sleep and sleeping gets shorter',
    followUp: { promptId: 'sleep:onset-minutes', windowHours: 16 },
    observationWindow: 'next-morning',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Out of the bedroom is most of it',
    fallback: 'Put it face down and out of reach',
    stoppingPoint: 'Once it is out of the room',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [later('energy-and-recovery', 'meaningful')],
    version: V,
  },
  {
    patternId: 'wind-down:stop-for-tonight',
    familyId: 'wind-down',
    statement: 'Stop for tonight. Protect sleep.',
    distinctBecause:
      'Not an action — the explicit instruction to do nothing further, when the hour says so.',
    intendedOutcome: 'Tomorrow starts from a better place than tonight would have reached',
    followUp: { promptId: 'sleep:bedtime', windowHours: 14 },
    observationWindow: 'next-morning',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Close what you are doing without finishing it',
    fallback: 'Set the time you will stop, and stop then',
    stoppingPoint: 'Immediately. That is the point.',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'supported',
    contradicts: [
      'protect-a-block:deep-block',
      'protect-a-block:short-block',
      'move-body:longer-walk',
    ],
    effects: [guards('energy-and-recovery', 'large')],
    version: V,
  },
  {
    patternId: 'wind-down:set-a-cutoff',
    familyId: 'wind-down',
    statement: 'Decide now what time you will stop tonight',
    distinctBecause:
      'Acts earlier in the day, when stopping is still cheap to agree to and not yet a sacrifice.',
    intendedOutcome: 'The evening ends at a time you chose rather than the time it ran out',
    followUp: { promptId: 'sleep:bedtime', windowHours: 14 },
    observationWindow: 'next-morning',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Name the hour out loud',
    fallback: 'Set an alarm for the time you meant to stop',
    stoppingPoint: 'When the time is set',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through'), guards('energy-and-recovery')],
    version: V,
  },

  /* --- settle-attention ---------------------------------------------------- */
  {
    patternId: 'settle-attention:sit-quietly',
    familyId: 'settle-attention',
    statement: 'Sit quietly for ten minutes',
    distinctBecause: 'The unstructured version, needing privacy but no method.',
    intendedOutcome: 'The intended task actually begins afterwards',
    followUp: { promptId: 'outcome:started', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'Three minutes with your eyes closed',
    fallback: 'Thirty seconds of slower breathing where you are',
    stoppingPoint: 'Ten minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    capacity: { shape: 'protected-focus', interruptionCost: 'partial' },
    effects: [lift('emotional-regulation'), later('focus-and-clarity', 'meaningful')],
    version: V,
  },
  {
    patternId: 'settle-attention:breathe-briefly',
    familyId: 'settle-attention',
    statement: 'Take a minute of slower breathing before the next thing',
    distinctBecause: 'The version that fits between two meetings and survives being overheard.',
    intendedOutcome: 'You start the next thing rather than carrying the last one into it',
    followUp: { promptId: 'outcome:started', windowHours: 2 },
    observationWindow: 'immediate',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Three slow breaths',
    fallback: 'Pause with your hand off the keyboard for a moment',
    stoppingPoint: 'One minute',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'settle-attention:name-the-loop',
    familyId: 'settle-attention',
    statement: 'Write down the thing you keep going back to',
    distinctBecause:
      'For rumination specifically — the problem is a loop, not tiredness or noise.',
    intendedOutcome: 'The same thought stops interrupting the next hour',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 4 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One sentence is enough',
    fallback: 'Say it out loud once',
    stoppingPoint: 'When it is written down',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [lift('emotional-regulation', 'meaningful'), later('focus-and-clarity')],
    version: V,
  },
  /* --- protect-a-block ----------------------------------------------------- */
  {
    patternId: 'protect-a-block:deep-block',
    familyId: 'protect-a-block',
    statement: 'Protect a block for the thing that matters most today',
    distinctBecause: 'The full-length version, when a real window exists to defend.',
    intendedOutcome: 'The block is started and the goal moves',
    followUp: { promptId: 'outcome:completed', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 45,
    minimumMinutes: 20,
    minimumVersion: 'Twenty minutes still counts',
    fallback: 'Write down the single next step instead',
    stoppingPoint: 'Stop at the end of the block whatever the progress',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'supported',
    capacity: { shape: 'exclusive-time', interruptionCost: 'total' },
    effects: [lift('focus-and-clarity', 'meaningful'), costs('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'protect-a-block:short-block',
    familyId: 'protect-a-block',
    statement: 'Take twenty minutes on it now',
    distinctBecause: 'Fits a gap rather than needing a window cleared for it.',
    intendedOutcome: 'The work is genuinely touched today rather than deferred',
    followUp: { promptId: 'outcome:started', windowHours: 12 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes, on the hardest part',
    fallback: 'Open the file and read the last thing you wrote',
    stoppingPoint: 'Twenty minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    capacity: { shape: 'exclusive-time', interruptionCost: 'partial' },
    effects: [lift('focus-and-clarity'), lift('follow-through')],
    version: V,
  },
  {
    patternId: 'protect-a-block:book-it',
    familyId: 'protect-a-block',
    statement: 'Put the block in the calendar for tomorrow',
    distinctBecause:
      'Acts when today has no room — the only member of the family that costs no time today.',
    intendedOutcome: 'Tomorrow contains a window that exists before the day starts',
    followUp: { promptId: 'outcome:completed', windowHours: 36 },
    observationWindow: 'multi-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Name the hour, even without an invite',
    fallback: 'Decide which day it will be',
    stoppingPoint: 'Once it is in',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'protect-a-block:defend-the-one-you-have',
    familyId: 'protect-a-block',
    statement: 'Decline the thing that would eat the block you already have',
    distinctBecause:
      'Protects an existing window rather than creating one. The obstacle is a person, not the diary.',
    intendedOutcome: 'The block that existed this morning still exists this afternoon',
    followUp: { promptId: 'outcome:completed', windowHours: 12 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Send the message saying you cannot',
    fallback: 'Offer a different time rather than accepting this one',
    stoppingPoint: 'Once the reply is sent',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [guards('focus-and-clarity', 'meaningful'), costs('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'protect-a-block:first-thing',
    familyId: 'protect-a-block',
    statement: 'Do it first tomorrow, before anything else opens',
    distinctBecause:
      'Uses time of day as the protection rather than a decision — nobody competes for it.',
    intendedOutcome: 'The thing gets touched before the day can take it',
    followUp: { promptId: 'outcome:started', windowHours: 30 },
    observationWindow: 'next-morning',
    durationMinutes: 30,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes before you open anything else',
    fallback: 'Leave it open on the desk overnight',
    stoppingPoint: 'When the rest of the day starts',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful'), lift('focus-and-clarity')],
    version: V,
  },

  /* --- smallest-next-step -------------------------------------------------- */
  {
    patternId: 'smallest-next-step:name-it',
    familyId: 'smallest-next-step',
    statement: 'Write down the single next physical action',
    distinctBecause:
      'For when the block is that the next step is unknown, not that it is hard.',
    intendedOutcome: 'The next step exists as a sentence rather than a feeling',
    followUp: { promptId: 'outcome:completed', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One line, starting with a verb',
    fallback: 'Say it out loud',
    stoppingPoint: 'When it is written',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    effects: [lift('follow-through', 'meaningful'), lift('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:two-minute-version',
    familyId: 'smallest-next-step',
    statement: 'Do the two-minute version of it now',
    distinctBecause: 'For when the step is known and the block is starting.',
    intendedOutcome: 'The thing is no longer untouched',
    followUp: { promptId: 'outcome:started', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 2,
    minimumMinutes: 2,
    minimumVersion: 'Two minutes is already the minimum',
    fallback: 'Open whatever you would need to open',
    stoppingPoint: 'Two minutes, then stop whether or not you want to',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'supported',
    capacity: { shape: 'transition', interruptionCost: 'none' },
    effects: [lift('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:split-it',
    familyId: 'smallest-next-step',
    statement: 'Break it into the first three steps and do none of them yet',
    distinctBecause:
      'For a thing too large to start rather than too vague — the output is structure, not progress.',
    intendedOutcome: 'The next session begins without a decision at the front of it',
    followUp: { promptId: 'outcome:completed', windowHours: 36 },
    observationWindow: 'multi-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Just the first step, written',
    fallback: 'Name the part you are avoiding',
    stoppingPoint: 'Three steps. Not a plan.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through'), lift('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:finish-the-nearly-done',
    familyId: 'smallest-next-step',
    statement: 'Finish the thing that is nearly done',
    distinctBecause:
      'Targets accumulated near-complete work, which costs attention differently from stalled work.',
    intendedOutcome: 'One open thing is closed rather than several advanced',
    followUp: { promptId: 'outcome:completed', windowHours: 12 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'The last step only',
    fallback: 'Write down what done would mean for it',
    stoppingPoint: 'When it is finished, or twenty minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('follow-through', 'meaningful'), lift('confidence-and-courage')],
    version: V,
  },

  /* --- unblock-by-asking ---------------------------------------------------- */
  {
    patternId: 'unblock-by-asking:send-the-message',
    familyId: 'unblock-by-asking',
    statement: 'Send the one message that unblocks it',
    distinctBecause: 'The default when the blocker is a person and the ask is already clear.',
    intendedOutcome: 'The commitment is no longer waiting on this step',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Two sentences is enough',
    fallback: 'Note who you are waiting on and when you last asked',
    stoppingPoint: 'Stop once the message is sent',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'supported',
    capacity: { shape: 'transition', interruptionCost: 'none' },
    effects: [lift('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'unblock-by-asking:chase-once',
    familyId: 'unblock-by-asking',
    statement: 'Follow up on the thing you asked for and have not heard back about',
    distinctBecause:
      'The second ask, which is a different social act from the first and often the one not made.',
    intendedOutcome: 'You know whether it is coming rather than assuming',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'A one-line nudge',
    fallback: 'Decide the date after which you will stop waiting',
    stoppingPoint: 'One follow-up',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('follow-through')],
    version: V,
  },
  {
    patternId: 'unblock-by-asking:ask-for-help',
    familyId: 'unblock-by-asking',
    statement: 'Ask someone who would know',
    distinctBecause:
      'The blocker is missing knowledge rather than a missing reply — a different ask entirely.',
    intendedOutcome: 'The unknown that was stalling it is answered',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Write the question, even if you do not send it yet',
    fallback: 'Name who would know',
    stoppingPoint: 'Once you have asked',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('learning-and-capability'), lift('follow-through')],
    version: V,
  },
  {
    patternId: 'unblock-by-asking:hand-it-over',
    familyId: 'unblock-by-asking',
    statement: 'Give it to someone else properly',
    distinctBecause:
      'Removes the thing rather than advancing it. The only member that reduces total load.',
    intendedOutcome: 'It is genuinely off your list, not half-delegated',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 15,
    minimumMinutes: 10,
    minimumVersion: 'Say who it is going to and by when',
    fallback: 'Write down what handing it over would require',
    stoppingPoint: 'When they have it and know they have it',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('follow-through'), lift('energy-and-recovery')],
    version: V,
  },

  /* --- decide-and-close ------------------------------------------------------ */
  {
    patternId: 'decide-and-close:make-the-call',
    familyId: 'decide-and-close',
    statement: 'Make the decision you have been circling',
    distinctBecause: 'For a decision that has all its information and is costing attention.',
    intendedOutcome: 'The decision stops occupying background attention',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Write the decision down even if you tell nobody yet',
    fallback: 'Write what you would need to know to decide',
    stoppingPoint: 'When it is decided',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [lift('focus-and-clarity', 'meaningful'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'decide-and-close:set-a-deadline-for-deciding',
    familyId: 'decide-and-close',
    statement: 'Set the date by which you will decide, and stop thinking about it until then',
    distinctBecause:
      'For a decision that genuinely is not ready — buys back the attention without forcing it.',
    intendedOutcome: 'It stops being revisited daily without being resolved prematurely',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 3,
    minimumMinutes: 1,
    minimumVersion: 'Name the date',
    fallback: 'Name what has to happen before it can be decided',
    stoppingPoint: 'When the date is set',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('emotional-regulation'), later('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'decide-and-close:choose-the-reversible-one',
    familyId: 'decide-and-close',
    statement: 'Take the option you could undo, and move on',
    distinctBecause:
      'A tie-break rule rather than a decision — for when the options are close and the delay is the cost.',
    intendedOutcome: 'The decision is made and could be revisited if it was wrong',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Name which of the options is the reversible one',
    fallback: 'Note that the options are genuinely close',
    stoppingPoint: 'When it is chosen',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('follow-through'), lift('confidence-and-courage')],
    version: V,
  },

  /* --- prepare-the-ground ---------------------------------------------------- */
  {
    patternId: 'prepare-the-ground:clear-the-desk',
    familyId: 'prepare-the-ground',
    statement: 'Clear the space you are about to work in',
    distinctBecause: 'Physical setup, where the obstacle is the environment.',
    intendedOutcome: 'The next block starts without a tidy-up in front of it',
    followUp: { promptId: 'outcome:started', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Clear enough space for what you need',
    fallback: 'Move one thing out of the way',
    stoppingPoint: 'Five minutes. This is not tidying.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('focus-and-clarity'), lift('environmental-ease')],
    version: V,
  },
  {
    patternId: 'prepare-the-ground:gather-what-you-need',
    familyId: 'prepare-the-ground',
    statement: 'Put everything you will need within reach first',
    distinctBecause:
      'Prevents the mid-task interruption rather than the starting friction. Different failure mode.',
    intendedOutcome: 'The block runs without a trip to fetch something',
    followUp: { promptId: 'outcome:stopped-early', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'The one thing you always end up getting up for',
    fallback: 'Note what you had to go and get',
    stoppingPoint: 'When it is all to hand',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [guards('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'prepare-the-ground:lay-it-out-tonight',
    familyId: 'prepare-the-ground',
    statement: 'Set it up tonight for tomorrow morning',
    distinctBecause:
      'Spends cheap evening effort to remove expensive morning friction. A different currency.',
    intendedOutcome: 'Tomorrow morning has one fewer reason not to start',
    followUp: { promptId: 'outcome:started', windowHours: 20 },
    observationWindow: 'next-morning',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One thing, left where you will see it',
    fallback: 'Decide where you will start',
    stoppingPoint: 'When it is laid out',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'prepare-the-ground:remove-the-distraction',
    familyId: 'prepare-the-ground',
    statement: 'Put the thing that will interrupt you out of reach before you start',
    distinctBecause:
      'Acts on the competing pull rather than the setup — an obstacle that wants your attention.',
    intendedOutcome: 'The block runs without being broken by the usual thing',
    followUp: { promptId: 'outcome:stopped-early', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Another room is best; a drawer will do',
    fallback: 'Turn it face down',
    stoppingPoint: 'Once it is away',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [guards('focus-and-clarity', 'meaningful')],
    version: V,
  },

  /* --- find-out --------------------------------------------------------------- */
  {
    patternId: 'find-out:check-the-number',
    familyId: 'find-out',
    statement: 'Look up the actual figure rather than estimating it again',
    distinctBecause: 'Replaces a repeatedly re-guessed number with a checked one.',
    intendedOutcome: 'The decision rests on a figure rather than an impression',
    followUp: { promptId: 'outcome:completed', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Find where the number lives, even if you do not read it yet',
    fallback: 'Write down what you think it is, to check later',
    stoppingPoint: 'When you have the figure',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [lift('learning-and-capability'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'find-out:read-one-thing',
    familyId: 'find-out',
    statement: 'Read the one thing that would settle it',
    distinctBecause:
      'Bounded reading against a specific question — the opposite of open-ended study.',
    intendedOutcome: 'The specific question is answered',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'The first section only',
    fallback: 'Write the question down so it stays specific',
    stoppingPoint: 'When the question is answered, not when the thing is finished',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'exclusive-time', interruptionCost: 'partial' },
    effects: [lift('learning-and-capability', 'meaningful')],
    version: V,
  },
  {
    patternId: 'find-out:try-it-small',
    familyId: 'find-out',
    statement: 'Try the smallest version and see what happens',
    distinctBecause:
      'Learning by doing rather than by reading, for questions that reading cannot settle.',
    intendedOutcome: 'You know something you could not have known by thinking about it',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'The crudest version that would still tell you something',
    fallback: 'Write down what you expect to happen',
    stoppingPoint: 'When you have learned the thing, however it went',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('learning-and-capability'), lift('confidence-and-courage')],
    version: V,
  },
  /* --- reach-out ------------------------------------------------------------- */
  {
    patternId: 'reach-out:message-someone',
    familyId: 'reach-out',
    statement: 'Send a message to someone you have not spoken to in a while',
    distinctBecause: 'The lowest-cost contact, available in any situation and at any hour.',
    intendedOutcome: 'Contact happens rather than being intended',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One line is a message',
    fallback: 'Write down who it would be',
    stoppingPoint: 'Once it is sent',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    capacity: { shape: 'transition', interruptionCost: 'none' },
    effects: [lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'reach-out:make-the-call',
    familyId: 'reach-out',
    statement: 'Ring them rather than messaging',
    distinctBecause:
      'A voice is a different act from text, and needs privacy and a window that text does not.',
    intendedOutcome: 'A real conversation happens',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes is a proper call',
    fallback: 'Send a message asking when would suit',
    stoppingPoint: 'When the conversation ends naturally',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'reach-out:arrange-something',
    familyId: 'reach-out',
    statement: 'Put something in the diary with them',
    distinctBecause:
      'Buys future contact rather than having it now — the version for when now is impossible.',
    intendedOutcome: 'Contact is scheduled rather than hoped for',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Suggest a week, not a date',
    fallback: 'Name who you would want to see',
    stoppingPoint: 'When a time is agreed',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [later('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'reach-out:say-the-appreciation',
    familyId: 'reach-out',
    statement: 'Tell someone the specific thing you appreciated',
    distinctBecause:
      'Gives rather than asks, and names something particular — a different act from checking in.',
    intendedOutcome: 'They know something they did not know',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One sentence, naming the specific thing',
    fallback: 'Write down what it was, to say later',
    stoppingPoint: 'Once it is said',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships'), lift('purpose-and-values-alignment')],
    version: V,
  },

  /* --- repair ----------------------------------------------------------------- */
  {
    patternId: 'repair:name-it-to-them',
    familyId: 'repair',
    statement: 'Say the thing that has been unsaid',
    distinctBecause: 'The direct repair, when both people know something is wrong.',
    intendedOutcome: 'The thing stops sitting between you unaddressed',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Say that there is something you want to talk about',
    fallback: 'Write down what you would want to say',
    stoppingPoint: 'When it has been said, not when it has been resolved',
    friction: 'high',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus', interruptionCost: 'total' },
    effects: [
      lift('connection-and-relationships', 'meaningful'),
      costs('emotional-regulation'),
    ],
    version: V,
  },
  {
    patternId: 'repair:apologise-specifically',
    familyId: 'repair',
    statement: 'Apologise for the specific thing, without explaining it',
    distinctBecause:
      'For when you were in the wrong. The explanation is the part that undoes it, so it is excluded.',
    intendedOutcome: 'They heard an apology rather than a defence',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Name the thing and say you are sorry for it',
    fallback: 'Write down what you would be apologising for',
    stoppingPoint: 'After the apology. Not after the discussion.',
    friction: 'high',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'repair:ask-what-they-need',
    familyId: 'repair',
    statement: 'Ask what would help, and then do that',
    distinctBecause:
      'For when you do not know what the repair is — the answer comes from them, not you.',
    intendedOutcome: 'The repair fits what they actually wanted',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Ask the question and listen to the answer',
    fallback: 'Ask when would be a good time to talk',
    stoppingPoint: 'When you know what they need',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'repair:let-it-settle',
    familyId: 'repair',
    statement: 'Leave it until tomorrow and say nothing tonight',
    distinctBecause:
      'The deliberate non-action, for when the repair would go badly right now. Doing nothing is the move.',
    intendedOutcome: 'The conversation happens when it can go well',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 36 },
    observationWindow: 'next-morning',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Decide not to raise it tonight',
    fallback: 'Write down what you would have said',
    stoppingPoint: 'Immediately. The point is not acting.',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [guards('connection-and-relationships'), lift('emotional-regulation')],
    version: V,
  },

  /* --- attend-to-child --------------------------------------------------------- */
  {
    patternId: 'attend-to-child:undivided-ten',
    familyId: 'attend-to-child',
    statement: 'Ten minutes with them and nothing else',
    distinctBecause: 'Short and total. The version that fits a working day.',
    intendedOutcome: 'They had your attention rather than your presence',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Five minutes with the phone in another room',
    fallback: 'Sit with them while they do their thing',
    stoppingPoint: 'Ten minutes, ended by you rather than by an interruption',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    capacity: { shape: 'exclusive-time', interruptionCost: 'partial' },
    effects: [lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'attend-to-child:follow-their-lead',
    familyId: 'attend-to-child',
    statement: 'Do the thing they choose, on their terms',
    distinctBecause:
      'Who decides is the variable, not the time. Different from being available.',
    intendedOutcome: 'The time was theirs rather than yours',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes of whatever they pick',
    fallback: 'Ask what they would like to do later',
    stoppingPoint: 'When they move on',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'attend-to-child:be-there-at-the-hinge',
    familyId: 'attend-to-child',
    statement: 'Be there for the part of the day that matters to them',
    distinctBecause:
      'Timing rather than duration — bedtime or the school gate, where absence is noticed.',
    intendedOutcome: 'You were present at the moment they would have missed you',
    followUp: { promptId: 'outcome:completed', windowHours: 24 },
    observationWindow: 'same-day',
    /* A bedtime or a school run is longer and less compressible than an arranged ten. */
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'The last ten minutes of it',
    fallback: 'Say in advance that you will be there tomorrow',
    stoppingPoint: 'When that part of the day is over',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'attend-to-child:notice-out-loud',
    familyId: 'attend-to-child',
    statement: 'Tell them the specific thing you noticed them do',
    distinctBecause:
      'Costs almost no time and is about being seen rather than being with. A different need.',
    intendedOutcome: 'They know you were paying attention',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'One sentence about one specific thing',
    fallback: 'Write down what you noticed',
    stoppingPoint: 'Once it is said',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships')],
    version: V,
  },

  /* --- reduce-friction-at-home -------------------------------------------------- */
  {
    patternId: 'reduce-friction-at-home:fix-the-repeat-offender',
    familyId: 'reduce-friction-at-home',
    statement: 'Change the thing that has got in the way more than once',
    distinctBecause: 'Targets a recurring friction specifically, not general tidying.',
    intendedOutcome: 'The same thing stops happening',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'The smallest change that would break the pattern',
    fallback: 'Write down exactly what keeps happening',
    stoppingPoint: 'When the change is made',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('environmental-ease', 'meaningful'), later('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'reduce-friction-at-home:put-it-where-it-is-used',
    familyId: 'reduce-friction-at-home',
    statement: 'Move the thing to where you actually use it',
    distinctBecause:
      'A placement change rather than a repair — cheap, and often the whole fix.',
    intendedOutcome: 'The small daily annoyance stops recurring',
    followUp: { promptId: 'outcome:completed', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Move one thing',
    fallback: 'Note where it should live',
    stoppingPoint: 'Once it is moved',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('environmental-ease')],
    version: V,
  },
  {
    patternId: 'reduce-friction-at-home:ten-minute-reset',
    familyId: 'reduce-friction-at-home',
    statement: 'Reset one room for ten minutes',
    distinctBecause:
      'Bounded and repeatable, aimed at accumulated state rather than a specific fault.',
    intendedOutcome: 'One space stops adding to the load',
    followUp: { promptId: 'outcome:duration', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'One surface',
    fallback: 'Clear the thing that bothers you most',
    stoppingPoint: 'Ten minutes, whatever state it is in',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('environmental-ease'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'reduce-friction-at-home:get-it-done-by-someone',
    familyId: 'reduce-friction-at-home',
    statement: 'Book someone to do the thing you keep not doing',
    distinctBecause:
      'Solves by spending money rather than time — the only member that does not need your hands.',
    intendedOutcome: 'It is handled without you having to become the person who does it',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Find out what it would cost',
    fallback: 'Write down what you would be paying someone to do',
    stoppingPoint: 'When it is booked',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [
      lift('environmental-ease', 'meaningful'),
      costs('financial-freedom-and-resilience'),
    ],
    version: V,
  },

  /* --- money-clarity ------------------------------------------------------------ */
  {
    patternId: 'money-clarity:look-at-it',
    familyId: 'money-clarity',
    statement: 'Look at the balance you have been avoiding',
    distinctBecause: 'The first act, when the problem is not looking rather than not knowing.',
    intendedOutcome: 'The number is known rather than imagined',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'Open it and close it again',
    fallback: 'Decide when this week you will look',
    stoppingPoint: 'When you have seen it',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [lift('emotional-regulation'), lift('financial-freedom-and-resilience')],
    version: V,
  },
  {
    patternId: 'money-clarity:name-the-worry',
    familyId: 'money-clarity',
    statement: 'Write down exactly what you are worried about, in one sentence',
    distinctBecause:
      'Turns a diffuse feeling into a specific claim, before any figure is involved.',
    intendedOutcome: 'The worry has a shape that can be checked',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One sentence',
    fallback: 'Say it out loud once',
    stoppingPoint: 'When it is written',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [lift('emotional-regulation', 'meaningful')],
    version: V,
  },
  {
    patternId: 'money-clarity:work-out-the-runway',
    familyId: 'money-clarity',
    statement: 'Work out how long the current position would last',
    distinctBecause:
      'A calculation rather than a look — answers "how long", which changes urgency.',
    intendedOutcome: 'Urgency is based on a timeframe rather than a feeling',
    followUp: { promptId: 'outcome:completed', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'A rough month count is enough to change the decision',
    fallback: 'Note the two figures you would need',
    stoppingPoint: 'When you have a number of months',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [
      lift('financial-freedom-and-resilience', 'meaningful'),
      lift('focus-and-clarity'),
    ],
    version: V,
  },

  /* --- money-guard --------------------------------------------------------------- */
  {
    patternId: 'money-guard:cancel-the-unused',
    familyId: 'money-guard',
    statement: 'Cancel the thing you are paying for and not using',
    distinctBecause: 'A one-off act with a recurring effect, and needs no negotiation.',
    intendedOutcome: 'A recurring cost stops recurring',
    followUp: { promptId: 'outcome:completed', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Cancel one',
    fallback: 'List what is going out that you do not use',
    stoppingPoint: 'When it is cancelled',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [lift('financial-freedom-and-resilience')],
    version: V,
  },
  {
    patternId: 'money-guard:delay-the-purchase',
    familyId: 'money-guard',
    statement: 'Put the purchase off for a week and see if you still want it',
    distinctBecause:
      'Prevents a future cost rather than removing a present one. Costs nothing to try.',
    intendedOutcome: 'The decision is made deliberately rather than in the moment',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Write down the date you will decide',
    fallback: 'Note what it was and what it cost',
    stoppingPoint: 'Immediately. The move is the not-buying.',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [guards('financial-freedom-and-resilience')],
    version: V,
  },
  {
    patternId: 'money-guard:talk-to-them-early',
    familyId: 'money-guard',
    statement: 'Contact them before it becomes a missed payment',
    distinctBecause:
      'Acts before the deadline, which is a materially different conversation from after it.',
    intendedOutcome: 'The situation is managed rather than escalated',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 20,
    minimumMinutes: 10,
    minimumVersion: 'Find out who to contact',
    fallback: 'Write down the date it becomes urgent',
    stoppingPoint: 'When you have spoken to them',
    friction: 'high',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [
      lift('financial-freedom-and-resilience', 'meaningful'),
      costs('emotional-regulation'),
    ],
    version: V,
  },

  /* --- live-the-value ------------------------------------------------------------ */
  {
    patternId: 'live-the-value:do-the-small-version',
    familyId: 'live-the-value',
    statement: 'Do two minutes of the thing you said you wanted to do',
    distinctBecause: 'The smallest possible act of alignment, available in any gap.',
    intendedOutcome: 'The week contains the thing rather than the intention',
    followUp: { promptId: 'outcome:started', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 2,
    minimumVersion: 'Two minutes is already the minimum',
    fallback: 'Name when today it would fit',
    stoppingPoint: 'Two minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('purpose-and-values-alignment')],
    version: V,
  },
  {
    patternId: 'live-the-value:make-room-for-it',
    familyId: 'live-the-value',
    statement: 'Put it in the week rather than hoping it happens',
    distinctBecause:
      'Schedules rather than does. For a value that keeps losing to whatever is louder.',
    intendedOutcome: 'It has a time rather than an intention',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Name the day',
    fallback: 'Note what keeps displacing it',
    stoppingPoint: 'When it is in',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('purpose-and-values-alignment', 'meaningful')],
    version: V,
  },
  {
    patternId: 'live-the-value:notice-the-gap',
    familyId: 'live-the-value',
    statement: 'Write down where this week did not match what you said matters',
    distinctBecause:
      'Observation rather than action — the point is the noticing, and it changes nothing today.',
    intendedOutcome: 'The gap is visible rather than vaguely felt',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'One place it did not match',
    fallback: 'Note that there was a gap',
    stoppingPoint: 'When it is written. No plan required.',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus' },
    effects: [lift('purpose-and-values-alignment'), lift('emotional-regulation')],
    version: V,
  },

  /* --- boundary -------------------------------------------------------------------- */
  {
    patternId: 'boundary:say-no-once',
    familyId: 'boundary',
    statement: 'Decline the next thing that does not fit',
    distinctBecause: 'A single refusal, not a rule. The cheapest way to test holding a line.',
    intendedOutcome: 'One thing that would have been accepted was not',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Say you cannot, without giving a reason',
    fallback: 'Write down what you would have declined',
    stoppingPoint: 'Once it is declined',
    friction: 'high',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [guards('energy-and-recovery'), costs('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'boundary:name-the-hours',
    familyId: 'boundary',
    statement: 'Tell the people who need to know when you are not available',
    distinctBecause:
      'A standing line rather than a single refusal, and it requires telling someone.',
    intendedOutcome:
      'The protected hours are known to the people who would otherwise fill them',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-week',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Tell the one person most likely to interrupt',
    fallback: 'Write down which hours you mean',
    stoppingPoint: 'Once they know',
    friction: 'high',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [guards('focus-and-clarity', 'meaningful'), guards('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'boundary:close-the-day',
    familyId: 'boundary',
    statement: 'Stop work at the time you said you would',
    distinctBecause:
      'A line against yourself rather than against another person. No one else is involved.',
    intendedOutcome: 'The evening starts when it was supposed to',
    followUp: { promptId: 'outcome:completed', windowHours: 16 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Close the laptop mid-sentence if you have to',
    fallback: 'Note what time you actually stopped',
    stoppingPoint: 'At the time. That is the whole move.',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    contradicts: ['protect-a-block:deep-block'],
    effects: [
      guards('energy-and-recovery', 'meaningful'),
      lift('connection-and-relationships'),
    ],
    version: V,
  },

  /* --- routine-anchor ---------------------------------------------------------------- */
  {
    patternId: 'routine-anchor:attach-to-existing',
    familyId: 'routine-anchor',
    statement: 'Attach it to something you already do every day',
    distinctBecause: 'Uses an existing habit as the trigger rather than relying on memory.',
    intendedOutcome: 'The thing happens without being remembered',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Name the existing thing it will follow',
    fallback: 'Note which daily thing would be the anchor',
    stoppingPoint: 'When the pairing is decided',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'routine-anchor:same-time-each-day',
    familyId: 'routine-anchor',
    statement: 'Do it at the same time each day for a week',
    distinctBecause:
      'Uses the clock rather than another habit — for when no suitable anchor exists.',
    intendedOutcome: 'It happens on more days than it did last week',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 3,
    minimumMinutes: 1,
    minimumVersion: 'Pick the time',
    fallback: 'Note the time it usually happens by accident',
    stoppingPoint: 'When the time is set',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through')],
    version: V,
  },
  {
    patternId: 'routine-anchor:shrink-it-until-it-sticks',
    familyId: 'routine-anchor',
    statement: 'Halve it until it happens every day, then leave it there',
    distinctBecause:
      'Changes the size rather than the timing, for a routine that keeps being skipped.',
    intendedOutcome: 'A smaller version happens reliably instead of a larger one failing',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 3,
    minimumMinutes: 1,
    minimumVersion: 'Decide the smaller size',
    fallback: 'Note how often it currently happens',
    stoppingPoint: 'When the smaller version is defined',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful')],
    version: V,
  },
  {
    patternId: 'routine-anchor:protect-the-wake-time',
    familyId: 'routine-anchor',
    statement: 'Get up at the same time tomorrow regardless of when you sleep',
    distinctBecause:
      'The one routine anchor with a physiological rationale, and the only one about sleep.',
    intendedOutcome: 'Tonight is easier to fall asleep at than last night',
    followUp: { promptId: 'sleep:wake-time', windowHours: 30 },
    observationWindow: 'next-morning',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Set the alarm before you go to bed',
    fallback: 'Note the time you actually woke',
    stoppingPoint: 'When the alarm is set',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [later('energy-and-recovery', 'meaningful')],
    version: V,
  },
  /* ------------------------------------------------------------------------ */
  /* Contextual variants                                                        */
  /*                                                                            */
  /* Same intent as a sibling above, shaped for a situation the base pattern    */
  /* cannot serve. Each earns its place by being possible where the base is not */
  /* — at a desk, with a child present, with five minutes, after a bad night.   */
  /* ------------------------------------------------------------------------ */

  {
    patternId: 'pause:at-desk',
    familyId: 'pause',
    statement: 'Take two minutes without leaving your desk',
    distinctBecause: 'Survives an open-plan office where stepping away would be noticed.',
    intendedOutcome: 'The next stretch starts from a slightly different place',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 2 },
    observationWindow: 'immediate',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'One minute looking away from the screen',
    fallback: 'Close your eyes for thirty seconds',
    stoppingPoint: 'Two minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'parallel' },
    effects: [lift('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'pause:with-a-child-present',
    familyId: 'pause',
    statement: 'Sit down with them for five minutes instead of pushing on',
    distinctBecause:
      'The version available when stepping away is not an option and they are there.',
    intendedOutcome: 'The push stops without anyone being left alone',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Sit down where they are',
    fallback: 'Stop what you are doing and watch them for a minute',
    stoppingPoint: 'Five minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'parallel' },
    effects: [lift('energy-and-recovery'), lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'move-body:after-a-bad-night',
    familyId: 'move-body',
    statement: 'Keep it to a short walk today rather than anything harder',
    distinctBecause:
      'Explicitly the reduced dose after poor sleep, so recovery is not treated as a normal day.',
    intendedOutcome: 'The day contains movement without borrowing against tonight',
    followUp: { promptId: 'outcome:completed', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Five minutes outside',
    fallback: 'Stand outside for a moment',
    stoppingPoint: 'Ten minutes. Today is not the day to extend it.',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [lift('energy-and-recovery'), guards('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'move-body:with-the-children',
    familyId: 'move-body',
    statement: 'Go out with them rather than going out alone',
    distinctBecause:
      'Serves two purposes in one window, for a day that has room for only one thing.',
    intendedOutcome: 'Movement happens and nobody is left behind for it',
    followUp: { promptId: 'outcome:completed', windowHours: 12 },
    observationWindow: 'same-day',
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'A short walk together',
    fallback: 'Suggest it for tomorrow',
    stoppingPoint: 'When they have had enough',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('energy-and-recovery'), lift('connection-and-relationships', 'meaningful')],
    version: V,
  },
  {
    patternId: 'settle-attention:before-the-hard-conversation',
    familyId: 'settle-attention',
    statement: 'Take a minute before you go in',
    distinctBecause:
      'Placed immediately before a specific difficult thing, rather than during a scattered stretch.',
    intendedOutcome: 'You start the conversation as you meant to',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 6 },
    observationWindow: 'immediate',
    durationMinutes: 1,
    minimumMinutes: 1,
    minimumVersion: 'Three breaths outside the door',
    fallback: 'Name what you want the outcome to be',
    stoppingPoint: 'One minute',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('emotional-regulation', 'meaningful')],
    version: V,
  },
  {
    patternId: 'settle-attention:between-roles',
    familyId: 'settle-attention',
    statement: 'Take five minutes between finishing work and being at home',
    distinctBecause:
      'A transition between two roles rather than a reset within one. Its own known failure point.',
    intendedOutcome: 'The evening does not inherit the day',
    followUp: { promptId: 'outcome:completed', windowHours: 6 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'Two minutes in the car before going in',
    fallback: 'Change out of what you worked in',
    stoppingPoint: 'Five minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'transition' },
    effects: [lift('emotional-regulation', 'meaningful'), lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'protect-a-block:with-the-house-full',
    familyId: 'protect-a-block',
    statement: 'Take a short block now and tell them you are taking it',
    distinctBecause:
      'For a house with people in it — the protection is telling them, not finding the time.',
    intendedOutcome: 'The block happens without becoming a source of friction',
    followUp: { promptId: 'outcome:completed', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 25,
    minimumMinutes: 15,
    minimumVersion: 'Fifteen minutes, announced',
    fallback: 'Agree a time later today',
    stoppingPoint: 'At the time you said you would stop',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('focus-and-clarity'), costs('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:when-you-cannot-face-it',
    familyId: 'smallest-next-step',
    statement: 'Do the least intimidating part first, out of order',
    distinctBecause:
      'For avoidance rather than confusion — sequence is sacrificed deliberately to get started.',
    intendedOutcome: 'The thing is started, from whichever end was possible',
    followUp: { promptId: 'outcome:started', windowHours: 12 },
    observationWindow: 'same-day',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Five minutes on the easiest part',
    fallback: 'Name which part you are avoiding',
    stoppingPoint: 'Fifteen minutes',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('follow-through'), lift('confidence-and-courage')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:on-a-phone',
    familyId: 'smallest-next-step',
    statement: 'Do the part of it that can be done from your phone',
    distinctBecause: 'The version available while out, with no desk and no laptop.',
    intendedOutcome: 'Progress happens in a window that would otherwise be dead',
    followUp: { promptId: 'outcome:started', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'The one message or the one note',
    fallback: 'Write yourself the note to act on later',
    stoppingPoint: 'When you are back at a desk',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'parallel' },
    effects: [lift('follow-through')],
    version: V,
  },
  {
    patternId: 'unblock-by-asking:when-it-is-awkward',
    familyId: 'unblock-by-asking',
    statement: 'Ask plainly, without apologising for asking',
    distinctBecause:
      'For when the ask is socially costly. The instruction is about how, not whether.',
    intendedOutcome: 'The ask is made and is understood as an ask',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'One sentence, no preamble',
    fallback: 'Write the sentence without sending it',
    stoppingPoint: 'Once it is sent',
    friction: 'high',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('follow-through'), lift('confidence-and-courage')],
    version: V,
  },
  {
    patternId: 'prepare-the-ground:for-the-morning-after-a-late-night',
    familyId: 'prepare-the-ground',
    statement: 'Make tomorrow morning need no decisions',
    distinctBecause:
      'Specifically for a morning you already know will be depleted, which changes what to prepare.',
    intendedOutcome: 'Tomorrow starts without needing willpower it will not have',
    followUp: { promptId: 'outcome:started', windowHours: 20 },
    observationWindow: 'next-morning',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'Decide the one thing tomorrow is for',
    fallback: 'Write down where to start',
    stoppingPoint: 'When nothing is left to decide',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through', 'meaningful'), later('focus-and-clarity')],
    version: V,
  },
  {
    patternId: 'find-out:ask-rather-than-research',
    familyId: 'find-out',
    statement: 'Ask the person who already knows instead of looking it up',
    distinctBecause:
      'Trades a social cost for a large time saving — the opposite trade from reading.',
    intendedOutcome: 'The answer arrives in minutes rather than hours',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Send the question',
    fallback: 'Write the question down precisely',
    stoppingPoint: 'Once it is asked',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('learning-and-capability'), lift('follow-through')],
    version: V,
  },
  {
    patternId: 'reach-out:when-you-have-no-energy',
    familyId: 'reach-out',
    statement: 'Send something short rather than nothing',
    distinctBecause:
      'Explicitly lowers the bar for a depleted day, when the alternative is no contact at all.',
    intendedOutcome: 'Contact happens at a size that was actually possible',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 48 },
    observationWindow: 'multi-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Three words is contact',
    fallback: 'Note who you meant to message',
    stoppingPoint: 'Once it is sent',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'attend-to-child:when-you-are-depleted',
    familyId: 'attend-to-child',
    statement: 'Be alongside them doing nothing in particular',
    distinctBecause:
      'Requires no energy to lead, for the evenings when the alternative is being absent.',
    intendedOutcome: 'They had company even though you had nothing left',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 15,
    minimumMinutes: 5,
    minimumVersion: 'Sit in the same room with your phone away',
    fallback: 'Say you are tired and still sit down with them',
    stoppingPoint: 'When one of you moves',
    friction: 'low',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'reduce-friction-at-home:the-five-minute-version',
    familyId: 'reduce-friction-at-home',
    statement: 'Do the five-minute version of the thing that has been waiting',
    distinctBecause:
      'For a day with no room. Explicitly partial, so partial does not read as failure.',
    intendedOutcome: 'It is smaller than it was',
    followUp: { promptId: 'outcome:duration', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 5,
    minimumMinutes: 3,
    minimumVersion: 'Three minutes',
    fallback: 'Note what the whole thing would take',
    stoppingPoint: 'Five minutes, unfinished on purpose',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('environmental-ease')],
    version: V,
  },
  {
    patternId: 'money-clarity:with-someone-else',
    familyId: 'money-clarity',
    statement: 'Look at it with the person it also affects',
    distinctBecause:
      'Turns a private act into a shared one, which changes both the difficulty and the outcome.',
    intendedOutcome: 'You are both looking at the same picture',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'Agree to look at it together this week',
    fallback: 'Say that you would like to go through it together',
    stoppingPoint: 'When you have both seen it',
    friction: 'high',
    safety: 'sensitive',
    lifecycle: 'experimental',
    capacity: { shape: 'protected-focus', interruptionCost: 'total' },
    effects: [
      lift('financial-freedom-and-resilience', 'meaningful'),
      lift('connection-and-relationships'),
    ],
    version: V,
  },
  {
    patternId: 'live-the-value:with-other-people',
    familyId: 'live-the-value',
    statement: 'Do it with someone rather than alone',
    distinctBecause:
      'Adds an external commitment, which is what makes it happen when doing it alone has not.',
    intendedOutcome: 'It happens because someone else is expecting it to',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 30,
    minimumMinutes: 15,
    minimumVersion: 'Ask one person',
    fallback: 'Name who you would ask',
    stoppingPoint: 'When it is arranged',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [
      lift('purpose-and-values-alignment', 'meaningful'),
      lift('connection-and-relationships'),
    ],
    version: V,
  },
  {
    patternId: 'boundary:for-one-evening',
    familyId: 'boundary',
    statement: 'Protect tonight only, and say nothing about the rest',
    distinctBecause:
      'A single evening rather than a standing rule — far cheaper to hold and to say.',
    intendedOutcome: 'One evening goes the way it was meant to',
    followUp: { promptId: 'outcome:completed', windowHours: 16 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Decide it, even without announcing it',
    fallback: 'Note what would have taken the evening',
    stoppingPoint: 'When the evening is over',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [guards('energy-and-recovery')],
    version: V,
  },
  {
    patternId: 'wind-down:when-it-is-already-late',
    familyId: 'wind-down',
    statement: 'Skip the wind-down and go to bed now',
    distinctBecause:
      'The routine costs more than it returns past a certain hour. Explicitly drops it.',
    intendedOutcome: 'Sleep starts sooner than it would have',
    followUp: { promptId: 'sleep:bedtime', windowHours: 14 },
    observationWindow: 'next-morning',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Stop and go',
    fallback: 'Set the time you will stop, for tomorrow',
    stoppingPoint: 'Immediately',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    contradicts: ['wind-down:start-now', 'protect-a-block:deep-block'],
    effects: [guards('energy-and-recovery', 'meaningful')],
    version: V,
  },
  {
    patternId: 'hydrate-eat:when-you-forgot-lunch',
    familyId: 'hydrate-eat',
    statement: 'Eat now, before the next thing, even if it is late',
    distinctBecause:
      'A prerequisite rather than a suggestion — nothing else will work until this is done.',
    intendedOutcome: 'The afternoon stops being explained by not having eaten',
    followUp: { promptId: 'outcome:still-interfering', windowHours: 3 },
    observationWindow: 'immediate',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Anything, now',
    fallback: 'Put something within reach',
    stoppingPoint: 'When you have eaten',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [lift('energy-and-recovery', 'meaningful')],
    version: V,
  },
  {
    patternId: 'decide-and-close:when-both-options-are-fine',
    familyId: 'decide-and-close',
    statement: 'Pick either one now and stop comparing them',
    distinctBecause:
      'For genuinely equivalent options, where the comparison itself is the only remaining cost.',
    intendedOutcome: 'The comparing stops',
    followUp: { promptId: 'outcome:decision-completed', windowHours: 24 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Say which one out loud',
    fallback: 'Write down that they are equivalent',
    stoppingPoint: 'Immediately',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('focus-and-clarity'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'repair:by-message-first',
    familyId: 'repair',
    statement: 'Send a short message opening the door, and leave it there',
    distinctBecause:
      'For when a conversation is not possible or not yet welcome. Lower cost to both.',
    intendedOutcome: 'The door is open whether or not they walk through it',
    followUp: { promptId: 'outcome:interaction-happened', windowHours: 72 },
    observationWindow: 'multi-day',
    durationMinutes: 5,
    minimumMinutes: 2,
    minimumVersion: 'One sentence with no expectation attached',
    fallback: 'Write what you would send',
    stoppingPoint: 'Once it is sent. Do not follow it.',
    friction: 'moderate',
    safety: 'interpersonal',
    lifecycle: 'experimental',
    effects: [lift('connection-and-relationships')],
    version: V,
  },
  {
    patternId: 'protect-a-block:the-fifteen-you-have',
    familyId: 'protect-a-block',
    statement: 'Use the fifteen minutes you actually have',
    distinctBecause:
      'For a fragmented day, where the honest answer is that no long block exists today.',
    intendedOutcome: 'The day contains some of the work rather than none',
    followUp: { promptId: 'outcome:started', windowHours: 8 },
    observationWindow: 'same-day',
    durationMinutes: 15,
    minimumMinutes: 10,
    minimumVersion: 'Ten minutes',
    fallback: 'Note where the fifteen minutes went',
    stoppingPoint: 'When the next thing starts',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    capacity: { shape: 'exclusive-time', interruptionCost: 'partial' },
    effects: [lift('focus-and-clarity'), lift('follow-through')],
    version: V,
  },
  {
    patternId: 'routine-anchor:for-the-phone',
    familyId: 'routine-anchor',
    statement: 'Put the phone on charge in another room at the same time each night',
    distinctBecause:
      'One specific recurring behaviour with a known effect, rather than a general anchor.',
    intendedOutcome: 'The evening ends earlier than it did last week',
    followUp: { promptId: 'sleep:bedtime', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Pick the time and the room',
    fallback: 'Note what time it usually happens',
    stoppingPoint: 'When the time is set',
    friction: 'moderate',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [later('energy-and-recovery', 'meaningful')],
    version: V,
  },
  {
    patternId: 'routine-anchor:for-the-laundry',
    familyId: 'routine-anchor',
    statement: 'Attach the washing to a day rather than to noticing the pile',
    distinctBecause:
      'A household routine whose failure mode is noticing too late, not forgetting how.',
    intendedOutcome: 'It stops being a thing that becomes urgent',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 3,
    minimumMinutes: 1,
    minimumVersion: 'Pick the day',
    fallback: 'Note which day it usually ends up being',
    stoppingPoint: 'When the day is chosen',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('environmental-ease'), later('follow-through')],
    version: V,
  },
  {
    patternId: 'money-guard:check-before-the-month-turns',
    familyId: 'money-guard',
    statement: 'Look at what is due before the month turns over',
    distinctBecause:
      'Timed to the billing cycle rather than to worry, which is when it can still change anything.',
    intendedOutcome: 'Nothing arrives as a surprise',
    followUp: { promptId: 'outcome:completed', windowHours: 168 },
    observationWindow: 'multi-week',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'The two largest ones',
    fallback: 'Note the date the month turns',
    stoppingPoint: 'When you have seen what is due',
    friction: 'low',
    safety: 'sensitive',
    lifecycle: 'experimental',
    effects: [guards('financial-freedom-and-resilience'), lift('emotional-regulation')],
    version: V,
  },
  {
    patternId: 'find-out:write-down-what-you-assumed',
    familyId: 'find-out',
    statement: 'Write down what you are assuming, then check only that',
    distinctBecause:
      'Narrows an open-ended investigation to the one belief actually carrying the decision.',
    intendedOutcome: 'The check is bounded rather than expanding',
    followUp: { promptId: 'outcome:completed', windowHours: 48 },
    observationWindow: 'same-day',
    durationMinutes: 10,
    minimumMinutes: 3,
    minimumVersion: 'Write the assumption down',
    fallback: 'Name which assumption matters most',
    stoppingPoint: 'When the assumption is written',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [lift('focus-and-clarity'), lift('learning-and-capability')],
    version: V,
  },
  {
    patternId: 'smallest-next-step:with-fifteen-minutes-left',
    familyId: 'smallest-next-step',
    statement: 'Set up the next session rather than starting the work',
    distinctBecause:
      'For a window too short to make progress in but long enough to remove tomorrow’s friction.',
    intendedOutcome: 'The next session starts faster than this one did',
    followUp: { promptId: 'outcome:started', windowHours: 30 },
    observationWindow: 'next-morning',
    durationMinutes: 10,
    minimumMinutes: 5,
    minimumVersion: 'Write the first step and leave it open',
    fallback: 'Note where you got to',
    stoppingPoint: 'When the next session is set up',
    friction: 'low',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [later('follow-through')],
    version: V,
  },
  {
    patternId: 'pause:instead-of-pushing-through',
    familyId: 'pause',
    statement: 'Stop now rather than finishing badly',
    distinctBecause:
      'A judgement about the current work rather than a break — the output would be poor anyway.',
    intendedOutcome: 'What was done is worth having, and the rest is done later properly',
    followUp: { promptId: 'outcome:stopped-early', windowHours: 6 },
    observationWindow: 'same-day',
    durationMinutes: 2,
    minimumMinutes: 1,
    minimumVersion: 'Close it where it is',
    fallback: 'Note where the quality dropped off',
    stoppingPoint: 'Immediately',
    friction: 'moderate',
    safety: 'routine',
    lifecycle: 'experimental',
    effects: [guards('energy-and-recovery'), later('focus-and-clarity')],
    version: V,
  },
];
