import { assertContextualCaptures, type ContextualCapture } from '../capture/contextualCapture';
import { ALL_PROMPTS } from '../prompts/definitions';

/**
 * Where every home question belongs (Prompt 8G).
 *
 * ## One guide-eligible question, and only because it changes what is possible
 *
 * `home:conditions` is the single capture here allowed into a daily check-in, on the same
 * grounds emotional interference earned its place in Prompt 8E: whether the room is too
 * loud right now decides whether a focus block is worth suggesting at all. It changes
 * candidate eligibility, not merely the record.
 *
 * Everything else is deliberate, action-linked, or unexpected. Nothing recurs, and
 * **nothing is triggered by time passing** — a home capture that fired because it had
 * been a week would be a chore reminder, whatever the wording said.
 */

export const HOME_CAPTURES: readonly ContextualCapture[] = [
  {
    id: 'home:friction',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'update-this-area',
    owningSurface: 'update-this-area',
    promptId: 'update-area:home-and-environment',
    eligibleGuides: [],
    triggers: ['The owner opened this area'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 6,
    duplicateSuppression: 'One reading per opening of this area',
    cooldownHours: 0,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: true,
  },
  {
    /**
     * The one question here that may interrupt.
     *
     * Triggered rather than recurring: asked when a focus or study action is being
     * considered and the conditions are unknown, never on a timetable.
     */
    id: 'home:conditions',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'triggered-domain-question',
    owningSurface: 'guide',
    promptId: 'home:conditions',
    eligibleGuides: [],
    triggers: [
      'A focus or study action is being considered and the conditions are unknown',
      'A friction about noise, light, or privacy was recorded in the last day',
    ],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep', 'commute'],
    freshnessHours: 4,
    duplicateSuppression: 'One answer per four hours',
    cooldownHours: 4,
    repeatedSkip: 'back-off',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: true,
  },
  {
    id: 'home:access',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'update-this-area',
    owningSurface: 'update-this-area',
    promptId: 'home:access',
    eligibleGuides: [],
    triggers: ['The owner opened this area'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 12,
    duplicateSuppression: 'One reading per opening of this area',
    cooldownHours: 0,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: false,
  },
  {
    id: 'home:setup-time',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'update-this-area',
    owningSurface: 'update-this-area',
    promptId: 'home:setup-time',
    eligibleGuides: [],
    triggers: ['The owner opened this area'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 12,
    duplicateSuppression: 'One reading per opening of this area',
    cooldownHours: 0,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: false,
  },
  {
    id: 'home:transition',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'update-this-area',
    owningSurface: 'update-this-area',
    promptId: 'home:transition',
    eligibleGuides: [],
    triggers: ['The owner opened this area'],
    parentingContext: 'A space that serves more than one use in a day',
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 24,
    duplicateSuppression: 'One reading per opening of this area',
    cooldownHours: 0,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: false,
  },
  {
    /** Naming the change is deliberate, and never asked in passing. */
    id: 'home:change-named',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'update-this-area',
    owningSurface: 'update-this-area',
    promptId: 'home:change-named',
    eligibleGuides: [],
    triggers: ['The same friction has been recorded more than once'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep', 'commute'],
    freshnessHours: 24 * 7,
    duplicateSuppression: 'One named change at a time, ever',
    cooldownHours: 24,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: true,
  },
  {
    id: 'home:change-made',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'action-follow-up',
    owningSurface: 'decision-episode',
    promptId: 'home:change-made',
    eligibleGuides: [],
    triggers: ['A change was named and the action was started'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 24,
    duplicateSuppression: 'One answer per named change',
    cooldownHours: 0,
    repeatedSkip: 'back-off',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: 'home:make-the-change',
    followUpWindowHours: 48,
    expiresAfterHours: 96,
    canAffectCurrentDecision: false,
  },
  {
    /**
     * The long follow-up, and the only one in the product measured in weeks.
     *
     * Whether an environment change held is not visible the next morning. Asking then
     * would collect an opinion; asking after a fortnight collects an observation.
     */
    id: 'home:friction-again',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'action-follow-up',
    owningSurface: 'decision-episode',
    promptId: 'home:friction-again',
    eligibleGuides: [],
    triggers: ['A change was made and a fortnight of ordinary use has passed'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 24 * 14,
    duplicateSuppression: 'One answer per change made',
    cooldownHours: 24 * 7,
    repeatedSkip: 'back-off',
    skipWritesNothing: true,
    offersUnsure: true,
    linkedAction: 'home:make-the-change',
    followUpWindowHours: 24 * 14,
    expiresAfterHours: 24 * 28,
    canAffectCurrentDecision: true,
  },
  {
    /** The unexpected event, through the compact manual route. */
    id: 'home:something-in-the-way',
    domainId: 'home-and-environment',
    recordFamily: 'observation',
    captureClass: 'quick-capture',
    owningSurface: 'quick-capture',
    promptId: 'home:something-in-the-way',
    eligibleGuides: [],
    triggers: ['The owner hit something and wanted it on record before he forgot'],
    parentingContext: undefined,
    privacy: 'general',
    excludedContexts: ['sleep'],
    freshnessHours: 0,
    duplicateSuppression: 'None — every entry is its own record',
    cooldownHours: 0,
    repeatedSkip: 'owner-initiated',
    skipWritesNothing: true,
    offersUnsure: false,
    linkedAction: undefined,
    followUpWindowHours: undefined,
    expiresAfterHours: undefined,
    canAffectCurrentDecision: false,
    quickCaptureKind: 'Something got in the way',
  },
];

assertContextualCaptures(HOME_CAPTURES, new Set(ALL_PROMPTS.map((prompt) => prompt.promptId)));
